name: Release to Gradle Plugin Portal

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Setup act
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash -s -- -b "/usr/bin"
          # Use the micro image to speed up tests: https://nektosact.com/usage/runners.html          
          echo "-P ubuntu-latest=node:16-buster-slim" > $HOME/.actrc
      - name: Build
        run: ./gradlew build
      - name: Publish to Plugins portal
        env:
          PGP_SIGNING_KEY: ${{secrets.PGP_SIGNING_KEY}}
          PGP_SIGNING_KEY_PASSPHRASE: ${{secrets.PGP_SIGNING_KEY_PASSPHRASE}}
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{secrets.PLUGINS_PORTAL_KEY}} -Pgradle.publish.secret=${{secrets.PLUGIN_PORTAL_SECRET}}
